import { type Mesh } from "./mesh";

/**
 * Binary STL.
 *
 * Offered as a fallback for slicers with weak 3MF support. STL carries no
 * units, so the receiving slicer assumes millimetres — which happens to be
 * right here, but is an assumption 3MF does not have to make. See ADR-0007.
 */
export function meshToStl(mesh: Mesh): Uint8Array<ArrayBuffer> {
  const triangleCount = mesh.triangles.length / 3;
  const buffer = new ArrayBuffer(84 + triangleCount * 50);
  const view = new DataView(buffer);

  const header = "Punchcard generated by knitting-machine-punchcard-generator";
  for (let i = 0; i < Math.min(header.length, 80); i++) {
    view.setUint8(i, header.charCodeAt(i));
  }

  view.setUint32(80, triangleCount, true);

  let offset = 84;
  for (let t = 0; t < mesh.triangles.length; t += 3) {
    const vertices = [0, 1, 2].map((k) => {
      const index = mesh.triangles[t + k] * 3;
      return [
        mesh.positions[index],
        mesh.positions[index + 1],
        mesh.positions[index + 2],
      ] as const;
    });

    const [a, b, c] = vertices;
    const u = [b[0] - a[0], b[1] - a[1], b[2] - a[2]] as const;
    const v = [c[0] - a[0], c[1] - a[1], c[2] - a[2]] as const;
    const normal = [
      u[1] * v[2] - u[2] * v[1],
      u[2] * v[0] - u[0] * v[2],
      u[0] * v[1] - u[1] * v[0],
    ];
    const length = Math.hypot(normal[0], normal[1], normal[2]) || 1;

    for (let k = 0; k < 3; k++) {
      view.setFloat32(offset, normal[k] / length, true);
      offset += 4;
    }
    for (const vertex of vertices) {
      for (const value of vertex) {
        view.setFloat32(offset, value, true);
        offset += 4;
      }
    }

    view.setUint16(offset, 0, true);
    offset += 2;
  }

  return new Uint8Array(buffer);
}
